/* Generated by Yosys 0.64 (git sha1 8449dd470, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) [the-openroad-project/yosys] */

module Sync_FIFO_async_rst(clk, rst, wr_en, rd_en, full, empty, din, dout);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input wr_en;
  wire wr_en;
  input rd_en;
  wire rd_en;
  output full;
  wire full;
  output empty;
  wire empty;
  input [7:0] din;
  wire [7:0] din;
  output [7:0] dout;
  wire [7:0] dout;
  wire _0_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _10_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _11_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _12_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _13_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _14_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _15_;
  wire _160_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _1_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _2_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _3_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _4_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  wire _59_;
  wire _5_;
  wire _60_;
  wire _61_;
  wire _62_;
  wire _63_;
  wire _64_;
  wire _65_;
  wire _66_;
  wire _67_;
  wire _68_;
  wire _69_;
  wire _6_;
  wire _70_;
  wire _71_;
  wire _72_;
  wire _73_;
  wire _74_;
  wire _75_;
  wire _76_;
  wire _77_;
  wire _78_;
  wire _79_;
  wire _7_;
  wire _80_;
  wire _81_;
  wire _82_;
  wire _83_;
  wire _84_;
  wire _85_;
  wire _86_;
  wire _87_;
  wire _88_;
  wire _89_;
  wire _8_;
  wire _90_;
  wire _91_;
  wire _92_;
  wire _93_;
  wire _94_;
  wire _95_;
  wire _96_;
  wire _97_;
  wire _98_;
  wire _99_;
  wire _9_;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[10] ;
  wire [7:0] \mem[11] ;
  wire [7:0] \mem[12] ;
  wire [7:0] \mem[13] ;
  wire [7:0] \mem[14] ;
  wire [7:0] \mem[15] ;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[3] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[5] ;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[7] ;
  wire [7:0] \mem[8] ;
  wire [7:0] \mem[9] ;
  wire [4:0] rd_ptr;
  wire [4:0] wr_ptr;
  sky130_fd_sc_hd__xor2_1 _161_ (
    .A(rd_ptr[0]),
    .B(wr_ptr[0]),
    .X(_45_)
  );
  sky130_fd_sc_hd__xor2_1 _162_ (
    .A(rd_ptr[1]),
    .B(wr_ptr[1]),
    .X(_46_)
  );
  sky130_fd_sc_hd__xor2_1 _163_ (
    .A(rd_ptr[3]),
    .B(wr_ptr[3]),
    .X(_47_)
  );
  sky130_fd_sc_hd__xor2_1 _164_ (
    .A(wr_ptr[2]),
    .B(rd_ptr[2]),
    .X(_48_)
  );
  sky130_fd_sc_hd__nor4_1 _165_ (
    .A(_45_),
    .B(_46_),
    .C(_47_),
    .D(_48_),
    .Y(_49_)
  );
  sky130_fd_sc_hd__xnor2_1 _166_ (
    .A(rd_ptr[4]),
    .B(wr_ptr[4]),
    .Y(_50_)
  );
  sky130_fd_sc_hd__xor2_1 _167_ (
    .A(rd_ptr[4]),
    .B(wr_ptr[4]),
    .X(_51_)
  );
  sky130_fd_sc_hd__and2_0 _168_ (
    .A(_49_),
    .B(_50_),
    .X(empty)
  );
  sky130_fd_sc_hd__a21boi_0 _169_ (
    .A1(_49_),
    .A2(_50_),
    .B1_N(rd_en),
    .Y(_52_)
  );
  sky130_fd_sc_hd__nor2_1 _170_ (
    .A(dout[6]),
    .B(_52_),
    .Y(_53_)
  );
  sky130_fd_sc_hd__nor4bb_1 _171_ (
    .A(rd_ptr[1]),
    .B(rd_ptr[0]),
    .C_N(rd_ptr[3]),
    .D_N(rd_ptr[2]),
    .Y(_54_)
  );
  sky130_fd_sc_hd__nor4b_1 _172_ (
    .A(rd_ptr[1]),
    .B(rd_ptr[0]),
    .C(rd_ptr[2]),
    .D_N(rd_ptr[3]),
    .Y(_55_)
  );
  sky130_fd_sc_hd__nor4bb_1 _173_ (
    .A(rd_ptr[1]),
    .B(rd_ptr[2]),
    .C_N(rd_ptr[3]),
    .D_N(rd_ptr[0]),
    .Y(_56_)
  );
  sky130_fd_sc_hd__and4b_1 _174_ (
    .A_N(rd_ptr[0]),
    .B(rd_ptr[3]),
    .C(rd_ptr[2]),
    .D(rd_ptr[1]),
    .X(_57_)
  );
  sky130_fd_sc_hd__nor4bb_1 _175_ (
    .A(rd_ptr[3]),
    .B(rd_ptr[2]),
    .C_N(rd_ptr[1]),
    .D_N(rd_ptr[0]),
    .Y(_58_)
  );
  sky130_fd_sc_hd__nand2_1 _176_ (
    .A(\mem[3] [6]),
    .B(_58_),
    .Y(_59_)
  );
  sky130_fd_sc_hd__and4b_1 _177_ (
    .A_N(rd_ptr[1]),
    .B(rd_ptr[0]),
    .C(rd_ptr[3]),
    .D(rd_ptr[2]),
    .X(_60_)
  );
  sky130_fd_sc_hd__nor4b_1 _178_ (
    .A(rd_ptr[1]),
    .B(rd_ptr[0]),
    .C(rd_ptr[3]),
    .D_N(rd_ptr[2]),
    .Y(_61_)
  );
  sky130_fd_sc_hd__nor4b_1 _179_ (
    .A(rd_ptr[0]),
    .B(rd_ptr[3]),
    .C(rd_ptr[2]),
    .D_N(rd_ptr[1]),
    .Y(_62_)
  );
  sky130_fd_sc_hd__nor4bb_1 _180_ (
    .A(rd_ptr[0]),
    .B(rd_ptr[3]),
    .C_N(rd_ptr[2]),
    .D_N(rd_ptr[1]),
    .Y(_63_)
  );
  sky130_fd_sc_hd__nor4bb_1 _181_ (
    .A(rd_ptr[1]),
    .B(rd_ptr[3]),
    .C_N(rd_ptr[2]),
    .D_N(rd_ptr[0]),
    .Y(_64_)
  );
  sky130_fd_sc_hd__and4b_1 _182_ (
    .A_N(rd_ptr[2]),
    .B(rd_ptr[3]),
    .C(rd_ptr[0]),
    .D(rd_ptr[1]),
    .X(_65_)
  );
  sky130_fd_sc_hd__nor4bb_1 _183_ (
    .A(rd_ptr[0]),
    .B(rd_ptr[2]),
    .C_N(rd_ptr[3]),
    .D_N(rd_ptr[1]),
    .Y(_66_)
  );
  sky130_fd_sc_hd__and4_1 _184_ (
    .A(rd_ptr[1]),
    .B(rd_ptr[0]),
    .C(rd_ptr[3]),
    .D(rd_ptr[2]),
    .X(_67_)
  );
  sky130_fd_sc_hd__nor4_1 _185_ (
    .A(rd_ptr[1]),
    .B(rd_ptr[0]),
    .C(rd_ptr[3]),
    .D(rd_ptr[2]),
    .Y(_68_)
  );
  sky130_fd_sc_hd__and4b_1 _186_ (
    .A_N(rd_ptr[3]),
    .B(rd_ptr[2]),
    .C(rd_ptr[1]),
    .D(rd_ptr[0]),
    .X(_69_)
  );
  sky130_fd_sc_hd__nor4b_1 _187_ (
    .A(rd_ptr[1]),
    .B(rd_ptr[3]),
    .C(rd_ptr[2]),
    .D_N(rd_ptr[0]),
    .Y(_70_)
  );
  sky130_fd_sc_hd__a222oi_1 _188_ (
    .A1(\mem[12] [6]),
    .A2(_54_),
    .B1(_62_),
    .B2(\mem[2] [6]),
    .C1(_68_),
    .C2(\mem[0] [6]),
    .Y(_71_)
  );
  sky130_fd_sc_hd__a22oi_1 _189_ (
    .A1(\mem[8] [6]),
    .A2(_55_),
    .B1(_61_),
    .B2(\mem[4] [6]),
    .Y(_72_)
  );
  sky130_fd_sc_hd__a222oi_1 _190_ (
    .A1(\mem[9] [6]),
    .A2(_56_),
    .B1(_67_),
    .B2(\mem[15] [6]),
    .C1(_60_),
    .C2(\mem[13] [6]),
    .Y(_73_)
  );
  sky130_fd_sc_hd__a22o_1 _191_ (
    .A1(\mem[5] [6]),
    .A2(_64_),
    .B1(_70_),
    .B2(\mem[1] [6]),
    .X(_74_)
  );
  sky130_fd_sc_hd__a221oi_1 _192_ (
    .A1(\mem[6] [6]),
    .A2(_63_),
    .B1(_69_),
    .B2(\mem[7] [6]),
    .C1(_74_),
    .Y(_75_)
  );
  sky130_fd_sc_hd__a222oi_1 _193_ (
    .A1(\mem[14] [6]),
    .A2(_57_),
    .B1(_65_),
    .B2(\mem[11] [6]),
    .C1(_66_),
    .C2(\mem[10] [6]),
    .Y(_76_)
  );
  sky130_fd_sc_hd__and4_1 _194_ (
    .A(_59_),
    .B(_73_),
    .C(_75_),
    .D(_76_),
    .X(_77_)
  );
  sky130_fd_sc_hd__a41oi_1 _195_ (
    .A1(_52_),
    .A2(_71_),
    .A3(_72_),
    .A4(_77_),
    .B1(_53_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nor2_1 _196_ (
    .A(dout[5]),
    .B(_52_),
    .Y(_78_)
  );
  sky130_fd_sc_hd__nand2_1 _197_ (
    .A(\mem[8] [5]),
    .B(_55_),
    .Y(_79_)
  );
  sky130_fd_sc_hd__a222oi_1 _198_ (
    .A1(\mem[2] [5]),
    .A2(_62_),
    .B1(_68_),
    .B2(\mem[0] [5]),
    .C1(_66_),
    .C2(\mem[10] [5]),
    .Y(_80_)
  );
  sky130_fd_sc_hd__nand2_1 _199_ (
    .A(_79_),
    .B(_80_),
    .Y(_81_)
  );
  sky130_fd_sc_hd__a222oi_1 _200_ (
    .A1(\mem[6] [5]),
    .A2(_63_),
    .B1(_64_),
    .B2(\mem[5] [5]),
    .C1(_70_),
    .C2(\mem[1] [5]),
    .Y(_82_)
  );
  sky130_fd_sc_hd__a222oi_1 _201_ (
    .A1(\mem[14] [5]),
    .A2(_57_),
    .B1(_60_),
    .B2(\mem[13] [5]),
    .C1(_61_),
    .C2(\mem[4] [5]),
    .Y(_83_)
  );
  sky130_fd_sc_hd__a222oi_1 _202_ (
    .A1(\mem[12] [5]),
    .A2(_54_),
    .B1(_69_),
    .B2(\mem[7] [5]),
    .C1(_67_),
    .C2(\mem[15] [5]),
    .Y(_84_)
  );
  sky130_fd_sc_hd__a222oi_1 _203_ (
    .A1(\mem[9] [5]),
    .A2(_56_),
    .B1(_58_),
    .B2(\mem[3] [5]),
    .C1(_65_),
    .C2(\mem[11] [5]),
    .Y(_85_)
  );
  sky130_fd_sc_hd__nand4_1 _204_ (
    .A(_82_),
    .B(_83_),
    .C(_84_),
    .D(_85_),
    .Y(_86_)
  );
  sky130_fd_sc_hd__nor2_1 _205_ (
    .A(_81_),
    .B(_86_),
    .Y(_87_)
  );
  sky130_fd_sc_hd__a21oi_1 _206_ (
    .A1(_52_),
    .A2(_87_),
    .B1(_78_),
    .Y(_44_)
  );
  sky130_fd_sc_hd__nor2_1 _207_ (
    .A(dout[4]),
    .B(_52_),
    .Y(_88_)
  );
  sky130_fd_sc_hd__nand2_1 _208_ (
    .A(\mem[15] [4]),
    .B(_67_),
    .Y(_89_)
  );
  sky130_fd_sc_hd__a222oi_1 _209_ (
    .A1(\mem[6] [4]),
    .A2(_63_),
    .B1(_68_),
    .B2(\mem[0] [4]),
    .C1(_69_),
    .C2(\mem[7] [4]),
    .Y(_90_)
  );
  sky130_fd_sc_hd__a222oi_1 _210_ (
    .A1(\mem[3] [4]),
    .A2(_58_),
    .B1(_70_),
    .B2(\mem[1] [4]),
    .C1(_64_),
    .C2(\mem[5] [4]),
    .Y(_91_)
  );
  sky130_fd_sc_hd__a22oi_1 _211_ (
    .A1(\mem[14] [4]),
    .A2(_57_),
    .B1(_62_),
    .B2(\mem[2] [4]),
    .Y(_92_)
  );
  sky130_fd_sc_hd__nand3_1 _212_ (
    .A(_90_),
    .B(_91_),
    .C(_92_),
    .Y(_93_)
  );
  sky130_fd_sc_hd__a222oi_1 _213_ (
    .A1(\mem[13] [4]),
    .A2(_60_),
    .B1(_61_),
    .B2(\mem[4] [4]),
    .C1(_66_),
    .C2(\mem[10] [4]),
    .Y(_94_)
  );
  sky130_fd_sc_hd__a22oi_1 _214_ (
    .A1(\mem[8] [4]),
    .A2(_55_),
    .B1(_65_),
    .B2(\mem[11] [4]),
    .Y(_95_)
  );
  sky130_fd_sc_hd__a22oi_1 _215_ (
    .A1(\mem[12] [4]),
    .A2(_54_),
    .B1(_56_),
    .B2(\mem[9] [4]),
    .Y(_96_)
  );
  sky130_fd_sc_hd__nand4_1 _216_ (
    .A(_89_),
    .B(_94_),
    .C(_95_),
    .D(_96_),
    .Y(_97_)
  );
  sky130_fd_sc_hd__nor2_1 _217_ (
    .A(_93_),
    .B(_97_),
    .Y(_98_)
  );
  sky130_fd_sc_hd__a21oi_1 _218_ (
    .A1(_52_),
    .A2(_98_),
    .B1(_88_),
    .Y(_42_)
  );
  sky130_fd_sc_hd__a22oi_1 _219_ (
    .A1(\mem[3] [3]),
    .A2(_58_),
    .B1(_61_),
    .B2(\mem[4] [3]),
    .Y(_99_)
  );
  sky130_fd_sc_hd__nand2_1 _220_ (
    .A(\mem[8] [3]),
    .B(_55_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__a22oi_1 _221_ (
    .A1(\mem[12] [3]),
    .A2(_54_),
    .B1(_56_),
    .B2(\mem[9] [3]),
    .Y(_101_)
  );
  sky130_fd_sc_hd__a22oi_1 _222_ (
    .A1(\mem[11] [3]),
    .A2(_65_),
    .B1(_66_),
    .B2(\mem[10] [3]),
    .Y(_102_)
  );
  sky130_fd_sc_hd__a222oi_1 _223_ (
    .A1(\mem[5] [3]),
    .A2(_64_),
    .B1(_68_),
    .B2(\mem[0] [3]),
    .C1(_70_),
    .C2(\mem[1] [3]),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand2_1 _224_ (
    .A(_99_),
    .B(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nand3_1 _225_ (
    .A(_100_),
    .B(_101_),
    .C(_102_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__a222oi_1 _226_ (
    .A1(\mem[13] [3]),
    .A2(_60_),
    .B1(_62_),
    .B2(\mem[2] [3]),
    .C1(_69_),
    .C2(\mem[7] [3]),
    .Y(_106_)
  );
  sky130_fd_sc_hd__a222oi_1 _227_ (
    .A1(\mem[14] [3]),
    .A2(_57_),
    .B1(_63_),
    .B2(\mem[6] [3]),
    .C1(_67_),
    .C2(\mem[15] [3]),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand3_1 _228_ (
    .A(_52_),
    .B(_106_),
    .C(_107_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__o32a_1 _229_ (
    .A1(_104_),
    .A2(_105_),
    .A3(_108_),
    .B1(_52_),
    .B2(dout[3]),
    .X(_12_)
  );
  sky130_fd_sc_hd__nor2_1 _230_ (
    .A(dout[2]),
    .B(_52_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand2_1 _231_ (
    .A(\mem[4] [2]),
    .B(_61_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__a222oi_1 _232_ (
    .A1(\mem[2] [2]),
    .A2(_62_),
    .B1(_63_),
    .B2(\mem[6] [2]),
    .C1(\mem[7] [2]),
    .C2(_69_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__a222oi_1 _233_ (
    .A1(\mem[12] [2]),
    .A2(_54_),
    .B1(_57_),
    .B2(\mem[14] [2]),
    .C1(\mem[15] [2]),
    .C2(_67_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__a22oi_1 _234_ (
    .A1(\mem[8] [2]),
    .A2(_55_),
    .B1(_64_),
    .B2(\mem[5] [2]),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nand3_1 _235_ (
    .A(_111_),
    .B(_112_),
    .C(_113_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__a222oi_1 _236_ (
    .A1(\mem[3] [2]),
    .A2(_58_),
    .B1(_70_),
    .B2(\mem[1] [2]),
    .C1(_60_),
    .C2(\mem[13] [2]),
    .Y(_115_)
  );
  sky130_fd_sc_hd__a22oi_1 _237_ (
    .A1(\mem[10] [2]),
    .A2(_66_),
    .B1(_68_),
    .B2(\mem[0] [2]),
    .Y(_116_)
  );
  sky130_fd_sc_hd__a22oi_1 _238_ (
    .A1(\mem[9] [2]),
    .A2(_56_),
    .B1(_65_),
    .B2(\mem[11] [2]),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nand4_1 _239_ (
    .A(_110_),
    .B(_115_),
    .C(_116_),
    .D(_117_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nor2_1 _240_ (
    .A(_114_),
    .B(_118_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__a21oi_1 _241_ (
    .A1(_52_),
    .A2(_119_),
    .B1(_109_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nor2_1 _242_ (
    .A(dout[1]),
    .B(_52_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nand2_1 _243_ (
    .A(\mem[9] [1]),
    .B(_56_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__a222oi_1 _244_ (
    .A1(\mem[14] [1]),
    .A2(_57_),
    .B1(_63_),
    .B2(\mem[6] [1]),
    .C1(_70_),
    .C2(\mem[1] [1]),
    .Y(_122_)
  );
  sky130_fd_sc_hd__a222oi_1 _245_ (
    .A1(\mem[4] [1]),
    .A2(_61_),
    .B1(_62_),
    .B2(\mem[2] [1]),
    .C1(_69_),
    .C2(\mem[7] [1]),
    .Y(_123_)
  );
  sky130_fd_sc_hd__a22oi_1 _246_ (
    .A1(\mem[3] [1]),
    .A2(_58_),
    .B1(_68_),
    .B2(\mem[0] [1]),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nand3_1 _247_ (
    .A(_122_),
    .B(_123_),
    .C(_124_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__a222oi_1 _248_ (
    .A1(\mem[13] [1]),
    .A2(_60_),
    .B1(_64_),
    .B2(\mem[5] [1]),
    .C1(_65_),
    .C2(\mem[11] [1]),
    .Y(_126_)
  );
  sky130_fd_sc_hd__a22oi_1 _249_ (
    .A1(\mem[10] [1]),
    .A2(_66_),
    .B1(_67_),
    .B2(\mem[15] [1]),
    .Y(_127_)
  );
  sky130_fd_sc_hd__a22oi_1 _250_ (
    .A1(\mem[12] [1]),
    .A2(_54_),
    .B1(_55_),
    .B2(\mem[8] [1]),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nand4_1 _251_ (
    .A(_121_),
    .B(_126_),
    .C(_127_),
    .D(_128_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nor2_1 _252_ (
    .A(_125_),
    .B(_129_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__a21oi_1 _253_ (
    .A1(_52_),
    .A2(_130_),
    .B1(_120_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nor2_1 _254_ (
    .A(dout[0]),
    .B(_52_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nand2_1 _255_ (
    .A(\mem[10] [0]),
    .B(_66_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nand2_1 _256_ (
    .A(\mem[6] [0]),
    .B(_63_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__a222oi_1 _257_ (
    .A1(\mem[3] [0]),
    .A2(_58_),
    .B1(_64_),
    .B2(\mem[5] [0]),
    .C1(\mem[15] [0]),
    .C2(_67_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__a22oi_1 _258_ (
    .A1(\mem[14] [0]),
    .A2(_57_),
    .B1(_61_),
    .B2(\mem[4] [0]),
    .Y(_135_)
  );
  sky130_fd_sc_hd__a22oi_1 _259_ (
    .A1(\mem[8] [0]),
    .A2(_55_),
    .B1(_65_),
    .B2(\mem[11] [0]),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nand4_1 _260_ (
    .A(_133_),
    .B(_134_),
    .C(_135_),
    .D(_136_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__a222oi_1 _261_ (
    .A1(\mem[12] [0]),
    .A2(_54_),
    .B1(_69_),
    .B2(\mem[7] [0]),
    .C1(_56_),
    .C2(\mem[9] [0]),
    .Y(_138_)
  );
  sky130_fd_sc_hd__a22oi_1 _262_ (
    .A1(\mem[0] [0]),
    .A2(_68_),
    .B1(_70_),
    .B2(\mem[1] [0]),
    .Y(_139_)
  );
  sky130_fd_sc_hd__a22oi_1 _263_ (
    .A1(\mem[13] [0]),
    .A2(_60_),
    .B1(_62_),
    .B2(\mem[2] [0]),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nand4_1 _264_ (
    .A(_132_),
    .B(_138_),
    .C(_139_),
    .D(_140_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__nor2_1 _265_ (
    .A(_137_),
    .B(_141_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__a21oi_1 _266_ (
    .A1(_52_),
    .A2(_142_),
    .B1(_131_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nand3_1 _267_ (
    .A(rd_ptr[1]),
    .B(rd_ptr[0]),
    .C(_52_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__a41oi_1 _268_ (
    .A1(rd_ptr[1]),
    .A2(rd_ptr[0]),
    .A3(rd_ptr[2]),
    .A4(_52_),
    .B1(rd_ptr[3]),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nand2_1 _269_ (
    .A(_52_),
    .B(_67_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__a21oi_1 _270_ (
    .A1(_52_),
    .A2(_67_),
    .B1(_144_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__xnor2_1 _271_ (
    .A(rd_ptr[2]),
    .B(_143_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__a21oi_1 _272_ (
    .A1(rd_ptr[0]),
    .A2(_52_),
    .B1(rd_ptr[1]),
    .Y(_146_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _273_ (
    .A(_143_),
    .SLEEP(_146_),
    .X(_18_)
  );
  sky130_fd_sc_hd__xor2_1 _274_ (
    .A(rd_ptr[0]),
    .B(_52_),
    .X(_19_)
  );
  sky130_fd_sc_hd__and2_0 _275_ (
    .A(_49_),
    .B(_51_),
    .X(full)
  );
  sky130_fd_sc_hd__a21boi_0 _276_ (
    .A1(_49_),
    .A2(_51_),
    .B1_N(wr_en),
    .Y(_147_)
  );
  sky130_fd_sc_hd__nand2_1 _277_ (
    .A(wr_ptr[0]),
    .B(_147_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__nand2_1 _278_ (
    .A(wr_ptr[1]),
    .B(wr_ptr[0]),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nand2_1 _279_ (
    .A(wr_ptr[2]),
    .B(wr_ptr[3]),
    .Y(_150_)
  );
  sky130_fd_sc_hd__clkinv_1 _280_ (
    .A(_150_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__nand4_1 _281_ (
    .A(wr_ptr[2]),
    .B(wr_ptr[1]),
    .C(wr_ptr[0]),
    .D(_147_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nand4_1 _282_ (
    .A(wr_ptr[1]),
    .B(wr_ptr[0]),
    .C(_147_),
    .D(_151_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__xnor2_1 _283_ (
    .A(wr_ptr[3]),
    .B(_152_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__a31oi_1 _284_ (
    .A1(wr_ptr[1]),
    .A2(wr_ptr[0]),
    .A3(_147_),
    .B1(wr_ptr[2]),
    .Y(_154_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _285_ (
    .A(_152_),
    .SLEEP(_154_),
    .X(_21_)
  );
  sky130_fd_sc_hd__xnor2_1 _286_ (
    .A(wr_ptr[1]),
    .B(_148_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__xor2_1 _287_ (
    .A(wr_ptr[0]),
    .B(_147_),
    .X(_23_)
  );
  sky130_fd_sc_hd__nor2_1 _288_ (
    .A(dout[7]),
    .B(_52_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__nand2_1 _289_ (
    .A(\mem[3] [7]),
    .B(_58_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__a22oi_1 _290_ (
    .A1(\mem[13] [7]),
    .A2(_60_),
    .B1(_64_),
    .B2(\mem[5] [7]),
    .Y(_157_)
  );
  sky130_fd_sc_hd__a222oi_1 _291_ (
    .A1(\mem[12] [7]),
    .A2(_54_),
    .B1(_55_),
    .B2(\mem[8] [7]),
    .C1(_67_),
    .C2(\mem[15] [7]),
    .Y(_158_)
  );
  sky130_fd_sc_hd__a222oi_1 _292_ (
    .A1(\mem[6] [7]),
    .A2(_63_),
    .B1(_68_),
    .B2(\mem[0] [7]),
    .C1(_69_),
    .C2(\mem[7] [7]),
    .Y(_159_)
  );
  sky130_fd_sc_hd__nand3_1 _293_ (
    .A(_156_),
    .B(_158_),
    .C(_159_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__a22oi_1 _294_ (
    .A1(\mem[14] [7]),
    .A2(_57_),
    .B1(_62_),
    .B2(\mem[2] [7]),
    .Y(_0_)
  );
  sky130_fd_sc_hd__a22oi_1 _295_ (
    .A1(\mem[4] [7]),
    .A2(_61_),
    .B1(_70_),
    .B2(\mem[1] [7]),
    .Y(_1_)
  );
  sky130_fd_sc_hd__a222oi_1 _296_ (
    .A1(\mem[11] [7]),
    .A2(_65_),
    .B1(_66_),
    .B2(\mem[10] [7]),
    .C1(\mem[9] [7]),
    .C2(_56_),
    .Y(_2_)
  );
  sky130_fd_sc_hd__nand4_1 _297_ (
    .A(_157_),
    .B(_0_),
    .C(_1_),
    .D(_2_),
    .Y(_3_)
  );
  sky130_fd_sc_hd__nor2_1 _298_ (
    .A(_160_),
    .B(_3_),
    .Y(_4_)
  );
  sky130_fd_sc_hd__a21oi_1 _299_ (
    .A1(_52_),
    .A2(_4_),
    .B1(_155_),
    .Y(_24_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _300_ (
    .A(wr_ptr[2]),
    .SLEEP(wr_ptr[3]),
    .X(_5_)
  );
  sky130_fd_sc_hd__nand2_1 _301_ (
    .A(rst),
    .B(_147_),
    .Y(_6_)
  );
  sky130_fd_sc_hd__nand4b_1 _302_ (
    .A_N(wr_ptr[0]),
    .B(rst),
    .C(_147_),
    .D(wr_ptr[1]),
    .Y(_7_)
  );
  sky130_fd_sc_hd__nor2_1 _303_ (
    .A(_5_),
    .B(_7_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__nand2b_1 _304_ (
    .A_N(wr_ptr[2]),
    .B(wr_ptr[3]),
    .Y(_8_)
  );
  sky130_fd_sc_hd__nor4_1 _305_ (
    .A(wr_ptr[1]),
    .B(wr_ptr[0]),
    .C(_6_),
    .D(_8_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__xnor2_1 _306_ (
    .A(rd_ptr[4]),
    .B(_145_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__xnor2_1 _307_ (
    .A(wr_ptr[4]),
    .B(_153_),
    .Y(_28_)
  );
  sky130_fd_sc_hd__nor3_1 _308_ (
    .A(_149_),
    .B(_6_),
    .C(_8_),
    .Y(_29_)
  );
  sky130_fd_sc_hd__nor2_1 _309_ (
    .A(_7_),
    .B(_8_),
    .Y(_30_)
  );
  sky130_fd_sc_hd__nand4b_1 _310_ (
    .A_N(wr_ptr[1]),
    .B(wr_ptr[0]),
    .C(rst),
    .D(_147_),
    .Y(_9_)
  );
  sky130_fd_sc_hd__nor2_1 _311_ (
    .A(_5_),
    .B(_9_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__nor3_1 _312_ (
    .A(_149_),
    .B(_150_),
    .C(_6_),
    .Y(_32_)
  );
  sky130_fd_sc_hd__nand2b_1 _313_ (
    .A_N(wr_ptr[3]),
    .B(wr_ptr[2]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nor3_1 _314_ (
    .A(_149_),
    .B(_6_),
    .C(_10_),
    .Y(_33_)
  );
  sky130_fd_sc_hd__nor4_1 _315_ (
    .A(wr_ptr[1]),
    .B(wr_ptr[0]),
    .C(_150_),
    .D(_6_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__nor2_1 _316_ (
    .A(_9_),
    .B(_10_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__nor2_1 _317_ (
    .A(_8_),
    .B(_9_),
    .Y(_36_)
  );
  sky130_fd_sc_hd__nor4_1 _318_ (
    .A(wr_ptr[1]),
    .B(wr_ptr[0]),
    .C(_6_),
    .D(_10_),
    .Y(_37_)
  );
  sky130_fd_sc_hd__nor2_1 _319_ (
    .A(_150_),
    .B(_7_),
    .Y(_38_)
  );
  sky130_fd_sc_hd__nor2_1 _320_ (
    .A(_7_),
    .B(_10_),
    .Y(_39_)
  );
  sky130_fd_sc_hd__nor4_1 _321_ (
    .A(wr_ptr[1]),
    .B(wr_ptr[0]),
    .C(_5_),
    .D(_6_),
    .Y(_40_)
  );
  sky130_fd_sc_hd__nor2_1 _322_ (
    .A(_150_),
    .B(_9_),
    .Y(_41_)
  );
  sky130_fd_sc_hd__nor3_1 _323_ (
    .A(_149_),
    .B(_5_),
    .C(_6_),
    .Y(_43_)
  );
  sky130_fd_sc_hd__edfxtp_1 _324_ (
    .CLK(clk),
    .D(din[4]),
    .DE(_33_),
    .Q(\mem[7] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _325_ (
    .CLK(clk),
    .D(din[3]),
    .DE(_33_),
    .Q(\mem[7] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _326_ (
    .CLK(clk),
    .D(din[2]),
    .DE(_33_),
    .Q(\mem[7] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _327_ (
    .CLK(clk),
    .D(din[4]),
    .DE(_32_),
    .Q(\mem[15] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _328_ (
    .CLK(clk),
    .D(din[1]),
    .DE(_33_),
    .Q(\mem[7] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _329_ (
    .CLK(clk),
    .D(din[0]),
    .DE(_33_),
    .Q(\mem[7] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _330_ (
    .CLK(clk),
    .D(din[6]),
    .DE(_40_),
    .Q(\mem[0] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _331_ (
    .CLK(clk),
    .D(din[5]),
    .DE(_40_),
    .Q(\mem[0] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _332_ (
    .CLK(clk),
    .D(din[4]),
    .DE(_40_),
    .Q(\mem[0] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _333_ (
    .CLK(clk),
    .D(din[3]),
    .DE(_40_),
    .Q(\mem[0] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _334_ (
    .CLK(clk),
    .D(din[2]),
    .DE(_40_),
    .Q(\mem[0] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _335_ (
    .CLK(clk),
    .D(din[3]),
    .DE(_32_),
    .Q(\mem[15] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _336_ (
    .CLK(clk),
    .D(din[1]),
    .DE(_40_),
    .Q(\mem[0] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _337_ (
    .CLK(clk),
    .D(din[0]),
    .DE(_40_),
    .Q(\mem[0] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _338_ (
    .CLK(clk),
    .D(din[6]),
    .DE(_31_),
    .Q(\mem[1] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _339_ (
    .CLK(clk),
    .D(din[5]),
    .DE(_31_),
    .Q(\mem[1] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _340_ (
    .CLK(clk),
    .D(din[4]),
    .DE(_31_),
    .Q(\mem[1] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _341_ (
    .CLK(clk),
    .D(din[3]),
    .DE(_31_),
    .Q(\mem[1] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _342_ (
    .CLK(clk),
    .D(din[2]),
    .DE(_31_),
    .Q(\mem[1] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _343_ (
    .CLK(clk),
    .D(din[2]),
    .DE(_32_),
    .Q(\mem[15] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _344_ (
    .CLK(clk),
    .D(din[1]),
    .DE(_31_),
    .Q(\mem[1] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _345_ (
    .CLK(clk),
    .D(din[0]),
    .DE(_31_),
    .Q(\mem[1] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _346_ (
    .CLK(clk),
    .D(din[6]),
    .DE(_25_),
    .Q(\mem[2] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _347_ (
    .CLK(clk),
    .D(din[5]),
    .DE(_25_),
    .Q(\mem[2] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _348_ (
    .CLK(clk),
    .D(din[4]),
    .DE(_25_),
    .Q(\mem[2] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _349_ (
    .CLK(clk),
    .D(din[3]),
    .DE(_25_),
    .Q(\mem[2] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _350_ (
    .CLK(clk),
    .D(din[2]),
    .DE(_25_),
    .Q(\mem[2] [2])
  );
  sky130_fd_sc_hd__dfrtp_1 _351_ (
    .CLK(clk),
    .D(_18_),
    .Q(rd_ptr[1]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__edfxtp_1 _352_ (
    .CLK(clk),
    .D(din[1]),
    .DE(_25_),
    .Q(\mem[2] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _353_ (
    .CLK(clk),
    .D(din[0]),
    .DE(_25_),
    .Q(\mem[2] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _354_ (
    .CLK(clk),
    .D(din[6]),
    .DE(_26_),
    .Q(\mem[8] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _355_ (
    .CLK(clk),
    .D(din[5]),
    .DE(_26_),
    .Q(\mem[8] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _356_ (
    .CLK(clk),
    .D(din[4]),
    .DE(_26_),
    .Q(\mem[8] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _357_ (
    .CLK(clk),
    .D(din[3]),
    .DE(_26_),
    .Q(\mem[8] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _358_ (
    .CLK(clk),
    .D(din[2]),
    .DE(_26_),
    .Q(\mem[8] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _359_ (
    .CLK(clk),
    .D(din[1]),
    .DE(_32_),
    .Q(\mem[15] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _360_ (
    .CLK(clk),
    .D(din[1]),
    .DE(_26_),
    .Q(\mem[8] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _361_ (
    .CLK(clk),
    .D(din[0]),
    .DE(_26_),
    .Q(\mem[8] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _362_ (
    .CLK(clk),
    .D(din[6]),
    .DE(_34_),
    .Q(\mem[12] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _363_ (
    .CLK(clk),
    .D(din[5]),
    .DE(_34_),
    .Q(\mem[12] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _364_ (
    .CLK(clk),
    .D(din[4]),
    .DE(_34_),
    .Q(\mem[12] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _365_ (
    .CLK(clk),
    .D(din[3]),
    .DE(_34_),
    .Q(\mem[12] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _366_ (
    .CLK(clk),
    .D(din[2]),
    .DE(_34_),
    .Q(\mem[12] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _367_ (
    .CLK(clk),
    .D(din[0]),
    .DE(_32_),
    .Q(\mem[15] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _368_ (
    .CLK(clk),
    .D(din[1]),
    .DE(_34_),
    .Q(\mem[12] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _369_ (
    .CLK(clk),
    .D(din[0]),
    .DE(_34_),
    .Q(\mem[12] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _370_ (
    .CLK(clk),
    .D(din[6]),
    .DE(_43_),
    .Q(\mem[3] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _371_ (
    .CLK(clk),
    .D(din[5]),
    .DE(_43_),
    .Q(\mem[3] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _372_ (
    .CLK(clk),
    .D(din[4]),
    .DE(_43_),
    .Q(\mem[3] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _373_ (
    .CLK(clk),
    .D(din[3]),
    .DE(_43_),
    .Q(\mem[3] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _374_ (
    .CLK(clk),
    .D(din[2]),
    .DE(_43_),
    .Q(\mem[3] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _375_ (
    .CLK(clk),
    .D(din[6]),
    .DE(_35_),
    .Q(\mem[5] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _376_ (
    .CLK(clk),
    .D(din[1]),
    .DE(_43_),
    .Q(\mem[3] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _377_ (
    .CLK(clk),
    .D(din[0]),
    .DE(_43_),
    .Q(\mem[3] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _378_ (
    .CLK(clk),
    .D(din[6]),
    .DE(_30_),
    .Q(\mem[10] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _379_ (
    .CLK(clk),
    .D(din[5]),
    .DE(_30_),
    .Q(\mem[10] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _380_ (
    .CLK(clk),
    .D(din[4]),
    .DE(_30_),
    .Q(\mem[10] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _381_ (
    .CLK(clk),
    .D(din[3]),
    .DE(_30_),
    .Q(\mem[10] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _382_ (
    .CLK(clk),
    .D(din[2]),
    .DE(_30_),
    .Q(\mem[10] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _383_ (
    .CLK(clk),
    .D(din[5]),
    .DE(_35_),
    .Q(\mem[5] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _384_ (
    .CLK(clk),
    .D(din[1]),
    .DE(_30_),
    .Q(\mem[10] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _385_ (
    .CLK(clk),
    .D(din[0]),
    .DE(_30_),
    .Q(\mem[10] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _386_ (
    .CLK(clk),
    .D(din[6]),
    .DE(_37_),
    .Q(\mem[4] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _387_ (
    .CLK(clk),
    .D(din[5]),
    .DE(_37_),
    .Q(\mem[4] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _388_ (
    .CLK(clk),
    .D(din[4]),
    .DE(_37_),
    .Q(\mem[4] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _389_ (
    .CLK(clk),
    .D(din[3]),
    .DE(_37_),
    .Q(\mem[4] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _390_ (
    .CLK(clk),
    .D(din[2]),
    .DE(_37_),
    .Q(\mem[4] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _391_ (
    .CLK(clk),
    .D(din[4]),
    .DE(_35_),
    .Q(\mem[5] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _392_ (
    .CLK(clk),
    .D(din[3]),
    .DE(_35_),
    .Q(\mem[5] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _393_ (
    .CLK(clk),
    .D(din[2]),
    .DE(_35_),
    .Q(\mem[5] [2])
  );
  sky130_fd_sc_hd__dfrtp_1 _394_ (
    .CLK(clk),
    .D(_17_),
    .Q(rd_ptr[2]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__edfxtp_1 _395_ (
    .CLK(clk),
    .D(din[1]),
    .DE(_37_),
    .Q(\mem[4] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _396_ (
    .CLK(clk),
    .D(din[1]),
    .DE(_35_),
    .Q(\mem[5] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _397_ (
    .CLK(clk),
    .D(din[0]),
    .DE(_37_),
    .Q(\mem[4] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _398_ (
    .CLK(clk),
    .D(din[0]),
    .DE(_35_),
    .Q(\mem[5] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _399_ (
    .CLK(clk),
    .D(din[6]),
    .DE(_36_),
    .Q(\mem[9] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _400_ (
    .CLK(clk),
    .D(din[5]),
    .DE(_36_),
    .Q(\mem[9] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _401_ (
    .CLK(clk),
    .D(din[4]),
    .DE(_36_),
    .Q(\mem[9] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _402_ (
    .CLK(clk),
    .D(din[3]),
    .DE(_36_),
    .Q(\mem[9] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _403_ (
    .CLK(clk),
    .D(din[2]),
    .DE(_36_),
    .Q(\mem[9] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _404_ (
    .CLK(clk),
    .D(din[7]),
    .DE(_39_),
    .Q(\mem[6] [7])
  );
  sky130_fd_sc_hd__dfrtp_1 _405_ (
    .CLK(clk),
    .D(_16_),
    .Q(rd_ptr[3]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _406_ (
    .CLK(clk),
    .D(_27_),
    .Q(rd_ptr[4]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__edfxtp_1 _407_ (
    .CLK(clk),
    .D(din[1]),
    .DE(_36_),
    .Q(\mem[9] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _408_ (
    .CLK(clk),
    .D(din[0]),
    .DE(_36_),
    .Q(\mem[9] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _409_ (
    .CLK(clk),
    .D(din[6]),
    .DE(_39_),
    .Q(\mem[6] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _410_ (
    .CLK(clk),
    .D(din[7]),
    .DE(_41_),
    .Q(\mem[13] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _411_ (
    .CLK(clk),
    .D(din[5]),
    .DE(_39_),
    .Q(\mem[6] [5])
  );
  sky130_fd_sc_hd__dfrtp_1 _412_ (
    .CLK(clk),
    .D(_28_),
    .Q(wr_ptr[4]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__edfxtp_1 _413_ (
    .CLK(clk),
    .D(din[7]),
    .DE(_33_),
    .Q(\mem[7] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _414_ (
    .CLK(clk),
    .D(din[4]),
    .DE(_39_),
    .Q(\mem[6] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _415_ (
    .CLK(clk),
    .D(din[3]),
    .DE(_39_),
    .Q(\mem[6] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _416_ (
    .CLK(clk),
    .D(din[2]),
    .DE(_39_),
    .Q(\mem[6] [2])
  );
  sky130_fd_sc_hd__dfrtp_1 _417_ (
    .CLK(clk),
    .D(_15_),
    .Q(dout[0]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__edfxtp_1 _418_ (
    .CLK(clk),
    .D(din[1]),
    .DE(_39_),
    .Q(\mem[6] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _419_ (
    .CLK(clk),
    .D(din[7]),
    .DE(_37_),
    .Q(\mem[4] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _420_ (
    .CLK(clk),
    .D(din[0]),
    .DE(_39_),
    .Q(\mem[6] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _421_ (
    .CLK(clk),
    .D(din[6]),
    .DE(_38_),
    .Q(\mem[14] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _422_ (
    .CLK(clk),
    .D(din[5]),
    .DE(_38_),
    .Q(\mem[14] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _423_ (
    .CLK(clk),
    .D(din[4]),
    .DE(_38_),
    .Q(\mem[14] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _424_ (
    .CLK(clk),
    .D(din[3]),
    .DE(_38_),
    .Q(\mem[14] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _425_ (
    .CLK(clk),
    .D(din[7]),
    .DE(_40_),
    .Q(\mem[0] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _426_ (
    .CLK(clk),
    .D(din[2]),
    .DE(_38_),
    .Q(\mem[14] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _427_ (
    .CLK(clk),
    .D(din[7]),
    .DE(_31_),
    .Q(\mem[1] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _428_ (
    .CLK(clk),
    .D(din[7]),
    .DE(_25_),
    .Q(\mem[2] [7])
  );
  sky130_fd_sc_hd__dfrtp_1 _429_ (
    .CLK(clk),
    .D(_14_),
    .Q(dout[1]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _430_ (
    .CLK(clk),
    .D(_13_),
    .Q(dout[2]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__edfxtp_1 _431_ (
    .CLK(clk),
    .D(din[7]),
    .DE(_26_),
    .Q(\mem[8] [7])
  );
  sky130_fd_sc_hd__dfrtp_1 _432_ (
    .CLK(clk),
    .D(_12_),
    .Q(dout[3]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__edfxtp_1 _433_ (
    .CLK(clk),
    .D(din[7]),
    .DE(_34_),
    .Q(\mem[12] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _434_ (
    .CLK(clk),
    .D(din[7]),
    .DE(_43_),
    .Q(\mem[3] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _435_ (
    .CLK(clk),
    .D(din[7]),
    .DE(_36_),
    .Q(\mem[9] [7])
  );
  sky130_fd_sc_hd__dfrtp_1 _436_ (
    .CLK(clk),
    .D(_42_),
    .Q(dout[4]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _437_ (
    .CLK(clk),
    .D(_44_),
    .Q(dout[5]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__edfxtp_1 _438_ (
    .CLK(clk),
    .D(din[7]),
    .DE(_35_),
    .Q(\mem[5] [7])
  );
  sky130_fd_sc_hd__dfrtp_1 _439_ (
    .CLK(clk),
    .D(_11_),
    .Q(dout[6]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__edfxtp_1 _440_ (
    .CLK(clk),
    .D(din[7]),
    .DE(_30_),
    .Q(\mem[10] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _441_ (
    .CLK(clk),
    .D(din[7]),
    .DE(_32_),
    .Q(\mem[15] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _442_ (
    .CLK(clk),
    .D(din[7]),
    .DE(_29_),
    .Q(\mem[11] [7])
  );
  sky130_fd_sc_hd__dfrtp_1 _443_ (
    .CLK(clk),
    .D(_24_),
    .Q(dout[7]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__edfxtp_1 _444_ (
    .CLK(clk),
    .D(din[7]),
    .DE(_38_),
    .Q(\mem[14] [7])
  );
  sky130_fd_sc_hd__dfrtp_1 _445_ (
    .CLK(clk),
    .D(_22_),
    .Q(wr_ptr[1]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__edfxtp_1 _446_ (
    .CLK(clk),
    .D(din[1]),
    .DE(_38_),
    .Q(\mem[14] [1])
  );
  sky130_fd_sc_hd__dfrtp_1 _447_ (
    .CLK(clk),
    .D(_19_),
    .Q(rd_ptr[0]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__edfxtp_1 _448_ (
    .CLK(clk),
    .D(din[6]),
    .DE(_41_),
    .Q(\mem[13] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _449_ (
    .CLK(clk),
    .D(din[5]),
    .DE(_41_),
    .Q(\mem[13] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _450_ (
    .CLK(clk),
    .D(din[4]),
    .DE(_41_),
    .Q(\mem[13] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _451_ (
    .CLK(clk),
    .D(din[3]),
    .DE(_41_),
    .Q(\mem[13] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _452_ (
    .CLK(clk),
    .D(din[2]),
    .DE(_41_),
    .Q(\mem[13] [2])
  );
  sky130_fd_sc_hd__dfrtp_1 _453_ (
    .CLK(clk),
    .D(_21_),
    .Q(wr_ptr[2]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__edfxtp_1 _454_ (
    .CLK(clk),
    .D(din[1]),
    .DE(_41_),
    .Q(\mem[13] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _455_ (
    .CLK(clk),
    .D(din[0]),
    .DE(_41_),
    .Q(\mem[13] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _456_ (
    .CLK(clk),
    .D(din[6]),
    .DE(_29_),
    .Q(\mem[11] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _457_ (
    .CLK(clk),
    .D(din[5]),
    .DE(_29_),
    .Q(\mem[11] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _458_ (
    .CLK(clk),
    .D(din[4]),
    .DE(_29_),
    .Q(\mem[11] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _459_ (
    .CLK(clk),
    .D(din[3]),
    .DE(_29_),
    .Q(\mem[11] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _460_ (
    .CLK(clk),
    .D(din[2]),
    .DE(_29_),
    .Q(\mem[11] [2])
  );
  sky130_fd_sc_hd__dfrtp_1 _461_ (
    .CLK(clk),
    .D(_20_),
    .Q(wr_ptr[3]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__edfxtp_1 _462_ (
    .CLK(clk),
    .D(din[0]),
    .DE(_29_),
    .Q(\mem[11] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _463_ (
    .CLK(clk),
    .D(din[0]),
    .DE(_38_),
    .Q(\mem[14] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _464_ (
    .CLK(clk),
    .D(din[6]),
    .DE(_32_),
    .Q(\mem[15] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _465_ (
    .CLK(clk),
    .D(din[5]),
    .DE(_32_),
    .Q(\mem[15] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _466_ (
    .CLK(clk),
    .D(din[1]),
    .DE(_29_),
    .Q(\mem[11] [1])
  );
  sky130_fd_sc_hd__dfrtp_1 _467_ (
    .CLK(clk),
    .D(_23_),
    .Q(wr_ptr[0]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__edfxtp_1 _468_ (
    .CLK(clk),
    .D(din[6]),
    .DE(_33_),
    .Q(\mem[7] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _469_ (
    .CLK(clk),
    .D(din[5]),
    .DE(_33_),
    .Q(\mem[7] [5])
  );
endmodule
